name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # node: ['10.x', '12.x', '14.x']
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        node: ["14.x"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      # - name: Lint
      #   run: cd react-menu-hook && yarn lint

      - name: Test
        run: cd react-menu-hook && yarn test --ci --coverage --maxWorkers=2

      - name: Type Check
        run: yarn type-check

      - name: Build
        run: cd react-menu-hook && yarn build
